# Generated by Django 4.0.3 on 2022-04-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(max_length=303),
        ),
        migrations.AlterField(
            model_name='post',
            name='Post_caption',
            field=models.CharField(blank=True, max_length=310),
        ),
    ]
